[app]
name = "扑克牌游戏"
env = "beta"
debug = false
version = "v0.0.1"
listen = 5099
host = "https://www.kakehotels.com:5099"
salt = "BWqzqzeCq8L$8obW"
google_secret = "DXQHUUBTVBVSFEIA"

[jwt]
secret = "U0042X2V^Lpb4OljBaHuinE$"

[aes]
key = "SFq3SIAPZY7t3mjj"
iv = "lR25Ojr5Nq9uv9Lu"

[cnf]
examine = 0
token_expire_hours = 24

[log]
gorm_log = true

[db]
connection = "mysql"
host = "127.0.0.1"
port = "4306"
database = "landlords"
username = "root"
password = "MySQL@9527"

[cache]
drive = "redis"

[redis]
host = "127.0.0.1"
port = "7379"
auth = "Redis@9527"
database = 0

[fs]
drive = "cos"
secret_id = ""
secret_key = ""
bucket = ""
region = "ap-shanghai"

[queue]
drive = "rabbit-mq"

[rabbit-mq]
host = "127.0.0.1"
port = "6672"
user = "admin"
pass = "Rabbit@9527"
vhost = "/"

[wx-applet]
app_id = "wx86d7b178fa31edf0"
app_secret = "44ccde490e7e211f91b07df39ef07b21"
